### ISSUE TITLE
- Add watch -> Try to standardize so in essence we want step 2, step 3 and step 4 as similar as possible.

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#102]

**Comment by bartmika** [comment]
@rodolfomartinez I need a decision.

In **residential** creation page, we have the fellowing.

![rez](https://user-images.githubusercontent.com/5767602/61426996-788f9480-a8ea-11e9-9911-d6494acc4fe0.png)

In **community cares** creation page, we have the following.

![cc](https://user-images.githubusercontent.com/5767602/61427024-94933600-a8ea-11e9-8ab4-086f48254b5c.png)

So my question is which one should we use for all the types?

**Comment by rodolfomartinez** [comment]
As long as (start) and finish) can be equal, so for example we could use 123 (start) 123 (finish) elm st., then the first option works great.
