### ISSUE TITLE
Area Coordinator / Associate

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#111]
- Members, Area Coordinator, Associate can be promoted or demoted
- When being promoted from member to coordinator then we need to fill in: (1) watch (2) police check (3) emergency contacts (4) sign confidentiality contract (5) sign coordinator agreement
- When being promoted from coordinator to associate we need to fill in: (1) Sign associate agreement

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, can you provide a list of requirements per promotion? Thanks!

**Comment by rodolfomartinez** [comment]
For promotion to coordinator from member:
Police check date
Area coordinator agreement
Conflict of interest policy
Code of conduct
Confidentiality agreement


For Associate
Associate agreement
