### ISSUE TITLE
Add Item > Incident 

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#118]
**Summary:**
After the modal described previously, we need the first step to be the following (radio button):

This incident involves the following:
Break In
Fraud
Arson
Assault
Illegal Drugs
Person in Need
A Public Safety Issue
Other

Step 2:
Have you notified the authorities of this Incident? (radio)
Yes
No

Step 3: (only photo field is optional)
Date:
Time:
Location:
Paragraph field:
Photo Upload

Step 4:
Please note that Neighbourhood Watch London cooperates with local authorities, and if requested by the police or a court order, a copy of this report will be made available to them.

Do you wish to proceed?
Yes
No

(if no, there is a modal with the following:)
Do you wish to erase and cancel this incident report?
Yes, erase
No, continue

Step 5 (if yes in step 4)
Review and Save

**Comment by bartmika** [comment]
@rodolfomartinez I will make a slight modification to the first step. It will be a dropdown instead of radio.

**Comment by bartmika** [comment]
@rodolfomartinez Step 2 and Step 4 should be merged.
