### ISSUE TITLE
Member - File "Incident" report

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#14]

**Comment by rodolfomartinez** [comment]
@bartmika - this should be the members "Item" function. Once a member has gone here from their dashboard, they should have tiles, with the following:
1. Community Event
2. Incident Report
3. Safety Issue
4. NWL Concern

**Comment by rodolfomartinez** [comment]
closing this; incident has been covered in #117 and #118 - will close this ticket and update others.
