### ISSUE TITLE
Add Item - Need descriptions for the items

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#147]
![Screen Shot 2019-07-29 at 8 47 02 PM](https://user-images.githubusercontent.com/5767602/62092155-2a5f8700-b242-11e9-9c16-f74c05b65122.png)

**Comment by rodolfomartinez** [comment]
Incident: Add an incident
Event: Add an event
Concern: Add a concern
Information: Add a resource
