### ISSUE TITLE
Concerns > Details screen

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#153]
**Summary:**
When someone clicks the "View" link from the Concerns table (see #151), there should be a summary type screen, with the fields from the creation, as well as a status field (which by default should be open) and similar to workery a tasks field with a button labelled "Review"

**Comment by bartmika** [comment]
@rodolfomartinez Can I get clarification on this issue?

**Comment by rodolfomartinez** [comment]
Need to QA existing Concern item. Will create new ticket afterwards
