### ISSUE TITLE
Move "Information" from "Items" to "Settings"

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#196]
**Summary:**
Move this item to settings and relabel to "News"

Change to have the following fields
Title
Description
URL
Expiry Date (MUST expire sometime)

Limited to 1 item which will be marquis in the app

**Comment by bartmika** [comment]
@rodolfomartinez My apologies I don't recall the context of this issue. Can we discuss?

**Comment by rodolfomartinez** [comment]
@bartmika - this was meant to create a news item (similar to office news) but it would create a sweet alert style banner at the top. So, if an Area Coordinator created this, it would be only for that watch. If an Associate created this it would be for their district, and if NWL staff created it it would be for everyone.

We can discuss in greater detail at a later date

**Comment by rodolfomartinez** [comment]
obsolete
