### ISSUE TITLE
New Settings Item

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#200]
**Summary:**
Report to Police URL
There should be a setting item where a report to police URL can be set in the system. So for example, the "london" tenant could have the london police online reporting URL

**Comment by bartmika** [comment]
Already implemented

**Comment by bartmika** [comment]
Misunderstanding

**Comment by rodolfomartinez** [comment]
@bartmika to clarify each org should have a setting for their online report to police URL

here is an example for London
https://www.coplogic.ca/dors/en/filing/selectincidenttype?dynparam=1584326750929
