### ISSUE TITLE
Cannot save changes to members

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#243]
**Summary:**
For this record
https://london.nwapp.ca/admin/member/sherri-abbott/update/contact
I changed the E-Mail/text consents, phone number, nd email using the update function, and got a confirmation, but no changes were saved.

**Comment by bartmika** [comment]
@rodolfomartinez @KHynds  Cannot replicate. If issue persists please re-open this ticket and provide instructions on replicating issue.
