### ISSUE TITLE
Staff - Manage Settings

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#26]

**Comment by rodolfomartinez** [comment]
@bartmika - is this the settings page? If so, then let's start with the following items:
Districts (fa icon: map-pin)
Tags ( fa icon: tag)
How Did you Hear (same icon as workery is OK)

**Comment by bartmika** [comment]
@rodolfomartinez I have enough for the **District** creation process but not for update. Can you advise?
