### ISSUE TITLE
Add Item > Volunteer

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#260]
Step 1:
Please choose an option (radio)
I want to help someone
I need help
Someone in my watch area needs help

Step 2:
Describe the volunteer post:
(text field 250 characters)

Step 3:
How often is this volunteer needed?
(dropdown)
One time
Once a week
Once a month

Step 4:
This volunteer post is open to:
(dropdown)
My Watch Area
All NW members

Step 5:
Review

**Comment by bartmika** [comment]
@rodolfomartinez I am going to make the following changes:
1. Change the order slightly
2. Will use "dropdown" instead of radio.
