### ISSUE TITLE
Update Announcement Bug?

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#269]
**Summary:**
When trying to edit/update an announcement, screen hangs. Refreshing brings back to edit screen, but changes cannot be made.
https://london.nwapp.ca/admin/settings/announcement/this-is-a-test-of-announcements/update

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I have been unable to replicate, can you provide details on browser / device / etc?

**Comment by rodolfomartinez** [comment]
Appears to be resolved.
