### ISSUE TITLE
Error when updating client

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#271]
**Summary:**
At this URL
https://london.nwapp.ca/admin/member/roger-adams/update/contact
I attempted to change the client's first name and phone number. Data appears to be valid, but this error was received:
Error(s):
Organization Name: This field must be unique.

Please make sure the above error(s) have been fixed before submitting again

![Screen Shot 2020-03-07 at 12 01 09 PM](https://user-images.githubusercontent.com/7537946/76147549-75a90600-606b-11ea-8669-6318bf9188a1.png)

**Comment by bartmika** [comment]
@rodolfomartinez Unable to replicate. Problem is that the database was wiped so I cannot replicate it. Can you try to replicate this error again with our new database?

**Comment by rodolfomartinez** [comment]
this seems much better, but for some reason changes to the first name field are not being saved. Take any record, go to the update > details view, change a first name, and you will see that changes are not saved, even though the dialogue confirms that they are

**Comment by bartmika** [comment]
@rodolfomartinez I confirm you have found a bug. Issue fixed!
