### ISSUE TITLE
Watch Edit Function for Clients?

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#272]
**Summary:**
For this client
https://london.nwapp.ca/admin/member/roger-adams/update/watch
I attempted to edit the watch area.
I was shown this: (note: I did update their address from 460-461)
![Screen Shot 2020-03-07 at 12 03 39 PM](https://user-images.githubusercontent.com/7537946/76147574-b30d9380-606b-11ea-966d-68d7539a8128.png)

Watches are blank, but watch areas are also tied to addresses, so the watch should only be editable to allow a transition to any virtual watch in the organization. Potential showstopper.

**Comment by bartmika** [comment]
@r
