### ISSUE TITLE
Should schema be editable?

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#283]
**Summary:**
I tried to edit the schema for london to "londonx"

I received a credentials validation error, but should this even be allowed? I can see some benefit if a group decides to rename, but wanted to see how we should handle the changing of schema (and not just org name). It is OK if we lock this out.

![23318A70-86FF-45EA-972D-A32BBF8AC19C](https://user-images.githubusercontent.com/7537946/77334229-e6eae900-6cfa-11ea-9685-f377140dc0fd.png)

**Comment by bartmika** [comment]
@rodolfomartinez Good discovery - modifying `schema_name` would have all sort of complications triggered with the database. As a result, I have disabled this field in the `update` section.
