### ISSUE TITLE
Address change and watch?

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#288]
**Summary:**
When updating someones address, should the system see if the new address is in the range for their existing watch? If not, I am not sure what should happen next. The easiest may be to "unassign" them from the watch, and then create a task for staff to assign them to their new watch. The biggest challenge I see is how do we handle this in the case of Area Coordinators. Moving them out would leave the watch without a coordinator.

**Comment by rodolfomartinez** [comment]
The alternative may be to do nothing new, apart from creating a task called "Review Watch" and the text would say
This person has moved watches, please review.

But, once clients have access to the app, how do we enable them to auto join the new watch?

**Comment by bartmika** [comment]
@rodolfomartinez We will need to discuss and commit to decision.

**Comment by rodolfomartinez** [comment]
As part of the process, we need to consider demotion. For example, if a normal member moves, then the address/watch matching should happen automatically, presenting the member with the Watch options screen.

If an Area Coordinator (AC) or Associate Member (AM) is moving, the following should happen:
They are first presented with an address search and watch options. Once an option is selected, this should happen:

for AC: You are about to move out of your current watch. You will lose your status as Area Coordinator, and you will become a general member of NW. If there is a vacancy in your new watch, you can become an Area Coordinator in your new Watch Area. Do you wish to proceed? Yes/No

for AM: You are about to move out of your current watch. You will lose your status as Area Coordinator, and you will become a general member of NW. If there is a vacancy in your new watch, you can become an Area Coordinator in your new Watch Area. If you are moving to a new ward, you will also lose your status as Associate Member. Do you wish to proceed? Yes/No

**Comment by bartmika** [comment]
@rodolfomartinez The simplest solution is as follows:

1. Everything works as expected
2. Create a "Report" which will generate a list of unmanaged wardens / watches. It will be the responsibility of the human to run the report and act upon it.

The benefit with this strategy is no special code is added, and the solution is simple.

**Comment by rodolfomartinez** [comment]
@bartmika I like this if we could combine it with the alert system we discussed earlier

Let's discuss further offline

**Comment by rodolfomartinez** [comment]
@bartmika - I like your solution, let’s implement it
