### ISSUE TITLE
Cannot create watch

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#296]
**Summary:**

Not certain if this has been addressed in dev, but when creating a watch and adding address info, the GUI validation does not accept the address range options. even when filled in correctly, it gives this:

![Screen Shot 2020-06-19 at 9 26 17 AM](https://user-images.githubusercontent.com/7537946/85137312-fa7cf180-b20e-11ea-9316-4d2e287bb327.png)

**Comment by bartmika** [comment]
@rodolfomartinez I cannot replicate, can you tell me the exact values you used to trigger this error?

Thank you!

**Comment by rodolfomartinez** [comment]
can no longe replicate
