### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by bartmika** [nwatchcanada/nwapp-front#3]
1. Firstname, lastname, etc
2. Validation messages
3. Redirect on success to register success page

**Comment by bartmika** [comment]
@rodolfomartinez How do we handle the following cases:

1. I am a home owner wanting to become a member for a specific tenant organization

2. I am a user who wants to start a tenant organization

3. How do I find which tenant I belong to?

**Comment by rodolfomartinez** [comment]
1. I would be directed via web or social media to my local tenant
2. This would happen via admin - user cannot directly launch a tenant
3. People will have the tenant's logo/name on their version of the app

**Comment by rodolfomartinez** [comment]
@bartmika - also please make sure that we follow the address conventions we discussed previously. I am assuming this is members sign up, so the process should begin with:
1.
Screen 1:
 Are you signing up as a....?
(a - biz/commercial tile) Business. (b - residential/housing) Individual

2. If they take the business path, then we need:

Screen 2 (business):
Business Name
Contact First Name, Contact Last Name
Contact Gender
Contact DOB (optional)
Primary Phone
Secondary Phone
Business Email
(address block)
How did you hear about us? (dropdown - Google, NWL Associate, NWL Area Coordinator, Facebook, twitter, Instagram, London Police Service, Other [with textbook])
What motivated you to download this app?
(dropdown - I want a safer community, I want to be more involved in my community, I want to learn more about my community, I want to learn more about Neighbourhood Watch, Other [with textbook])

I agree to:
(checkboxes)
Privacy Polocy
Terms & Conditions
To become a member of Neighbourhood Watch London

Screen 3 (for business):
Choose your area:

*this will be a dropdown with business districts*

3. If I chose Individual
Screen 2:
Contact First Name, Contact Last Name
Contact Gender
Contact DOB (optional)
Primary Phone
Secondary Phone 
Email
(address block)
How did you hear about us? (dropdown - Google, NWL Associate, NWL Area Coordinator, Facebook, twitter, Instagram, London Police Service, Other [with textbook])
What motivated you to download this app?
(dropdown - I want a safer community, I want to be more involved in my community, I want to learn more about my community, I want to learn more about Neighbourhood Watch, Other [with textbook])

Screen 3:

Dropdown 1: Choose Your Ward
(ward numbers 1-14.... last option is "I don't know)

If I don't know is chosen, go to 4a

Screen 4a:
NWL Staff will check your details, and will place you in the appropriate ward and watch. Please keep an eye on your email inbox.

Screen 4b (if user selected a valid ward): ***we need to discuss how this works***
You are almost there! Based on your street name, you should be in one of the following watches:
(list of applicable watches)

**This works great for housing, not sure how it will work for residential**

**Comment by rodolfomartinez** [comment]
@bartmika - maybe we should create v0.5 and v1.0 milestones and make this a 1.0? I feel like we need the admin piece clear before we can build logic for general members/users
