### ISSUE TITLE
Need all street type selections in dropdowns when adding member

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#304]
**Summary:**
When adding/editing a member, the dropdown for street type only shows "Drive" and "Other"

**Comment by bartmika** [comment]
@rodolfomartinez Cannot replicate, can you provide instructions on how to replicate? Thank you!

**Comment by rodolfomartinez** [comment]
We are still missing: 
Court
Crescent
Place
Lane
Grove
Boulevard (currently our entries use Blvd - how should we handle this?)
Terrace
Gate
Hill
