### ISSUE TITLE
secondary phone field

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#313]
**Summary:**
This was discussed during planning and sketching phase; please ensure that there is a secondary phone number field for all "people" type entries

**Comment by rodolfomartinez** [comment]
This should look and behave just like workery with the phone type etc

**Comment by bartmika** [comment]
Hi @rodolfomartinez, where do you want this field to appear?

**Comment by rodolfomartinez** [comment]
@bartmika - I think we can close this for now
