### ISSUE TITLE
Lost ability to access application

### ISSUE THREAD

**Issue by RaymondO55** [nwatchcanada/nwapp-front#314]
I restarted my computer and when I came back to the browser it gave me this constant loading issue. Trying to login on a new tab tells me that the email is no longer registered. Images provided below:

![Loading issue](https://user-images.githubusercontent.com/41381131/88419156-a5567180-cdb2-11ea-89d2-82c456998043.png)

![EmailNotRegistered](https://user-images.githubusercontent.com/41381131/88419163-a9828f00-cdb2-11ea-9db7-e66a205fd654.png)

**Comment by bartmika** [comment]
My apologies @RaymondO55, I forgot to create the admin account when I deployed the last build. I confirm this issue works now.
