### ISSUE TITLE
Can't Promote Area Coordinators to Associate

### ISSUE THREAD

**Issue by RaymondO55** [nwatchcanada/nwapp-front#317]
The promotion function only seems to work from member to another role. Member to AC, Member to Associate, Member to Staff and Member to Management all work

I have tested AC to Associate and Staff to Management and have run into the same problem. They get stuck at the confirmation page where clicking the save button refreshes the page but you cannot proceed from there

**Comment by bartmika** [comment]
Hi @RaymondO55! Long time no talk.

Confirmed this is a `500 Error`. Looking into fix.
