### ISSUE TITLE
NEW process for business members only.

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#325]
**Summary:**
Business Watches will be made up of large areas; significantly larger than residential areas. For this reason, can we change this process for business members ONLY

at URLs like
https://london.nwapp.ca/admin/members/add/step-6

list ALL business watches; do not validate against any address as entering business address ranges will be cumbersome. The user selects the one they want, and they proceed.

![Screen Shot 2020-08-17 at 2 42 23 PM](https://user-images.githubusercontent.com/7537946/90432071-00207780-e098-11ea-8ece-bfaef10d2473.png)

**Comment by bartmika** [comment]
@rodolfomartinez If this is the case, I strongly suggest that we make business watches all "Virtual" by default and that will save us development effort.

**Comment by rodolfomartinez** [comment]
@bartmika - they do need to be tied to a specific watch area, so Virtual won't necessarily work here.
