### ISSUE TITLE
Settings > support E-Mail

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#330]
**Summary:**
In settings, we need to add a tile/item called "Contact Info"

The following fields should be available:
E-Mail
Phone
website
facebook page
twitter
instagram
youtube

The only one that is required is email

**Comment by bartmika** [comment]
@rodolfomartinez 
> The only one that is required is email
I made phone and website required as well. Let me know if it works for your team.
