### ISSUE TITLE
District Creation - Residential

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#47]
**Summary:**
1. City Role Number and Legal Description can be removed.
2. Link to City Website - I think we can remove this as well.
3. Validation is not enforced for Counselor name, phone or email

**Comment by bartmika** [comment]
> Validation is not enforced for Counselor name, phone or email

@rodolfomartinez - Could not replicate. Please try again and if you can, please specify what you inputted.
