### ISSUE TITLE
District Creation - Business

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#48]
**Summary:**
For the logo upload, can we replace the text with an upload button, similar to 
https://london.workery.ca/en/members/summary/detail/6138/files/

**Comment by bartmika** [comment]
@rodolfomartinez I envision it should work something like this.

![dropzone](https://user-images.githubusercontent.com/5767602/59315554-2d99b600-8c88-11e9-9a5a-02e963caf14d.gif)

The GUI from workery will not do.
