### ISSUE TITLE
Add Item

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#57]
**Summary:**
When adding an item, we should use a tiled UI similar to choosing between residential, commercial etc., but with the item types from Trello

**Comment by bartmika** [comment]
@rodolfomartinez Just updated the "Add Item" to have the four options:

* Concern

* Event

* Incident

* Information

However, I will need more details as to what fields to collect inside each type of item.

**Comment by rodolfomartinez** [comment]
i) Concern:
Title - text
Description - text
Location - text
Photos - (optional, upload)

ii) Event
First, tiles with the following types:
- Garage Sale
- Gathering
- Sports
- BBQ/Fundraiser
- Arts
- Other

For all of these, we can have the following fields:
Name - text
Date - date picker
Description - text
Photo - optional, file upload

iii) Incident
Title - text
Date - date picker
Description - text
Location - text
Photos - (optional, upload)

iv) Information - these should come from "Settings" so I don't think we need to add "Information/Resources" from here

**Comment by bartmika** [comment]
@rodolfomartinez Implemented everything except **information** - will review now.
