### ISSUE TITLE
Add "Financials" to Project

### ISSUE THREAD

**Issue by rodolfomartinez** [nwatchcanada/nwapp-front#64]
**Summary:**
When viewing members, area coordinators or associates, can we use the workery views at this URL https://london.workery.ca/en/jobs/summary/ so that each individual has a "view" icon and a "financial" icon (which is only available to executive)

Also, for executive we need to add financials to hamburger menu

**Comment by bartmika** [comment]
@rodolfomartinez Implemented but used slightly different GUI.
